version: "3.6"
services:
  olm-src:
    build:
      context: .
      dockerfile: Dockerfile.git
    volumes:
      - "./ext-src/:/ext-src/:rw"
    environment:
      DET_LOCALSRC: olm
      DET_REPOSURL: "https://gitlab.matrix.org/matrix-org/olm.git"
  olm-lib:
    build:
      context: .
      dockerfile: Dockerfile.olm
    volumes:
      - "./ext-src/olm/:/ext-src/olm/:ro"
      - "./libolm/:/libolm/:rw"
  go-olm-src:
    build:
      context: .
      dockerfile: Dockerfile.git
    volumes:
      - "./ext-src/:/ext-src/:rw"
    environment:
      DET_LOCALSRC: go-olm
      DET_REPOSURL: "https://github.com/saces/go-olm.git"
  matrix-doc-src:
    build:
      context: .
      dockerfile: Dockerfile.git
    volumes:
      - "./ext-src/:/ext-src/:rw"
    environment:
      DET_LOCALSRC: matrix-doc
      DET_REPOS_PATCH_URL: "https://github.com/saces/matrix-doc.git"
      DET_REPOS_MATRIX_URL: "https://github.com/matrix-org/matrix-doc.git"
      DET_REPOS_MATRIX_BRANCH: "master"
      DET_REPOS_USER_NAME: "user"
      DET_REPOS_USER_EMAIL: "user@determina.nt"
  matrix-doc-gen:
    build:
      context: .
      dockerfile: Dockerfile.mdoc
    volumes:
      - "./ext-src/matrix-doc/:/ext-src/matrix-doc/:ro"
      - "./matrix-spec/:/matrix-spec/:rw"
  generate-client-api:
    build:
      context: .
      dockerfile: Dockerfile.gen
    volumes:
      - "./matrix-spec/:/matrix-spec/:ro"
      - "./generated-src/:/generated-src/:rw"
