FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    git \
    gcc \
    g++ \
    cmake \
    && rm -rf /var/lib/apt/lists/*

COPY ./docker-scripts/buildolm.sh /scripts/buildolm.sh

ENV PATH=$PATH:/scripts
CMD ["buildolm.sh"]