FROM golang:1.12-alpine as builder

RUN apk add git

RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger 


FROM alpine:latest
LABEL maintainer saces <saces@c-base.org>

COPY --from=builder /go/bin/ /go/bin/
COPY ./docker-scripts/go-swagger.sh /scripts/go-swagger.sh

CMD ["/scripts/go-swagger.sh"]
